<?php
class AdminLevelConfig {
	public static $ADMINLEVELS = array(
		/********************* ADMINLEVELS CONFIGURATION *********************/
		
		'SuperAdmin' => array(
			'adminlevel' => array(
				'type' => 'SuperAdmin',
			),
			'access' => array(
				'server_options',
				'game_infos',
				'chat',
				'maps_list',
				'maps_local',
				'maps_upload',
				'maps_order',
				'maps_matchsettings',
				'maps_create_matchsettings',
				'link_access_server',
				'plugins_list',
				'guest_ban',
			),
			'permission' => array(
				'speed_admin',
				'switch_server',
				'player_kick',
				'player_ban',
				'player_guest',
				'player_ignore',
				'player_forcetospectator',
				'player_forcetoplayer',
				'player_changeteam',
				'force_scores',
				'cancel_vote',
				'srvopts_general_name',
				'srvopts_general_comment',
				'srvopts_general_playerpassword',
				'srvopts_general_spectatorpassword',
				'srvopts_general_nbplayers',
				'srvopts_general_nbspectators',
				'srvopts_advanced',
				'srvopts_adminlevelpassword',
				'srvopts_importexport',
				'gameinfos_general_gamemode',
				'gameinfos_general_options',
				'gameinfos_general_warmup',
				'gameinfos_teams_options',
				'gameinfos_gamemode_options',
				'chat_sendmessage',
				'maps_list_moveaftercurrent',
				'maps_list_removetolist',
				'maps_local_add',
				'maps_local_insert',
				'maps_local_download',
				'maps_local_rename',
				'maps_local_move',
				'maps_local_delete',
				'maps_upload_add',
				'maps_upload_insert',
				'maps_upload_folder',
				'maps_matchsettings_save',
				'maps_matchsettings_load',
				'maps_matchsettings_add',
				'maps_matchsettings_insert',
				'maps_matchsettings_edit',
				'maps_matchsettings_delete',
				'folder_new',
				'folder_rename',
				'folder_move',
				'folder_delete',
				'guestban_addplayer',
				'guestban_removeplayer',
				'guestban_playlist_new',
				'guestban_playlist_save',
				'guestban_playlist_load',
				'guestban_playlist_delete',
			),
		),
		'Admin' => array(
			'adminlevel' => array(
				'type' => 'Admin',
			),
			'access' => array(
				'server_options',
				'game_infos',
				'chat',
				'maps_list',
				'maps_local',
				'maps_upload',
				'maps_order',
				'maps_matchsettings',
				'maps_create_matchsettings',
				'link_access_server',
				'plugins_list',
				'guest_ban',
			),
			'permission' => array(
				'speed_admin',
				'switch_server',
				'player_kick',
				'player_ban',
				'player_guest',
				'player_ignore',
				'player_forcetospectator',
				'player_forcetoplayer',
				'player_changeteam',
				'force_scores',
				'cancel_vote',
				'srvopts_general_name',
				'srvopts_general_comment',
				'srvopts_general_playerpassword',
				'srvopts_general_spectatorpassword',
				'srvopts_general_nbplayers',
				'srvopts_general_nbspectators',
				'gameinfos_general_gamemode',
				'gameinfos_general_warmup',
				'gameinfos_teams_options',
				'gameinfos_gamemode_options',
				'chat_sendmessage',
				'maps_list_moveaftercurrent',
				'maps_list_removetolist',
				'maps_local_add',
				'maps_local_insert',
				'maps_local_download',
				'maps_local_rename',
				'maps_local_move',
				'maps_upload_add',
				'maps_upload_insert',
				'maps_upload_folder',
				'maps_matchsettings_save',
				'maps_matchsettings_load',
				'maps_matchsettings_add',
				'maps_matchsettings_insert',
				'maps_matchsettings_edit',
				'folder_new',
				'folder_rename',
				'folder_move',
				'guestban_addplayer',
				'guestban_removeplayer',
				'guestban_playlist_new',
				'guestban_playlist_save',
				'guestban_playlist_load',
			),
		),
		'User' => array(
			'adminlevel' => array(
				'type' => 'User',
			),
			'access' => array(
				'chat',
				'maps_list',
				'link_access_server',
			),
			'permission' => array(
			),
		),
	);
}
?>